# Generated by Django 2.1 on 2019-04-23 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='password',
            options={'managed': True, 'verbose_name_plural': 'Passwords'},
        ),
        migrations.AlterModelTable(
            name='password',
            table='Password',
        ),
    ]
